export const flagListArray = {
    ad: {country: 'Andorra', ISO2: 'ad', mobileCode: '376'},
    ae: {country: 'United Arab Emirates', ISO2: 'ae', mobileCode: '971'},
    af: {country: 'Afghanistan', ISO2: 'af', mobileCode: '93'},
    ag: {country: 'Antigua and Barbuda', ISO2: 'ag', mobileCode: '1268'},
    ai: {country: 'Anguilla', ISO2: 'ai', mobileCode: '1264'},
    al: {country: 'Albania', ISO2: 'al', mobileCode: '355'},
    am: {country: 'Armenia', ISO2: 'am', mobileCode: '374'},
    an: {country: 'Netherlands Antilles', ISO2: 'an', mobileCode: '599'},
    ao: {country: 'Angola', ISO2: 'ao', mobileCode: '244'},
    ar: {country: 'Argentina', ISO2: 'ar', mobileCode: '54'},
    at: {country: 'Austria', ISO2: 'at', mobileCode: '43'},
    au: {country: 'Australia', ISO2: 'au', mobileCode: '61'},
    aw: {country: 'Aruba', ISO2: 'aw', mobileCode: '297'},
    az: {country: 'Azerbaijan', ISO2: 'az', mobileCode: '994'},
    ba: {country: 'Bosnia and Herzegovina', ISO2: 'ba', mobileCode: '387'},
    bb: {country: 'Barbados', ISO2: 'bb', mobileCode: '1246'},
    bd: {country: 'Bangladesh', ISO2: 'bd', mobileCode: '880'},
    be: {country: 'Belgium', ISO2: 'be', mobileCode: '32'},
    bf: {country: 'Burkina Faso', ISO2: 'bf', mobileCode: '226'},
    bg: {country: 'Bulgaria', ISO2: 'bg', mobileCode: '359'},
    bh: {country: 'Bahrain', ISO2: 'bh', mobileCode: '973'},
    bi: {country: 'Burundi', ISO2: 'bi', mobileCode: '257'},
    bj: {country: 'Benin', ISO2: 'bj', mobileCode: '229'},
    bm: {country: 'Bermuda', ISO2: 'bm', mobileCode: '1441'},
    bn: {country: 'Brunei', ISO2: 'bn', mobileCode: '673'},
    bo: {country: 'Bolivia', ISO2: 'bo', mobileCode: '591'},
    br: {country: 'Brazil', ISO2: 'br', mobileCode: '55'},
    bs: {country: 'Bahamas', ISO2: 'bs', mobileCode: '1242'},
    bt: {country: 'Bhutan', ISO2: 'bt', mobileCode: '975'},
    bw: {country: 'Botswana', ISO2: 'bw', mobileCode: '267'},
    by: {country: 'Belarus', ISO2: 'by', mobileCode: '375'},
    bz: {country: 'Belize', ISO2: 'bz', mobileCode: '501'},
    ca: {country: 'Canada', ISO2: 'ca', mobileCode: '1'},
    cd: {country: 'Democratic Republic of the Congo', ISO2: 'cd', mobileCode: '243'},
    cf: {country: 'Central African Republic', ISO2: 'cf', mobileCode: '236'},
    cg: {country: 'Republic of the Congo', ISO2: 'cg', mobileCode: '242'},
    ch: {country: 'Switzerland', ISO2: 'ch', mobileCode: '41'},
    ci: {country: 'Ivory Coast', ISO2: 'ci', mobileCode: '225'},
    ck: {country: 'Cook Islands', ISO2: 'ck', mobileCode: '682'},
    cl: {country: 'Chile', ISO2: 'cl', mobileCode: '56'},
    cm: {country: 'Cameroon', ISO2: 'cm', mobileCode: '237'},
    cn: {country: 'Republic of China', ISO2: 'cn', mobileCode: '86'},
    co: {country: 'Colombia', ISO2: 'co', mobileCode: '57'},
    cr: {country: 'Costa Rica', ISO2: 'cr', mobileCode: '506'},
    cu: {country: 'Cuba', ISO2: 'cu', mobileCode: '53'},
    cv: {country: 'Cape Verde', ISO2: 'cv', mobileCode: '238'},
    cx: {country: 'Christmas Island', ISO2: 'cx', mobileCode: '61'},
    cy: {country: 'Cyprus', ISO2: 'cy', mobileCode: '357'},
    cz: {country: 'Czech Republic', ISO2: 'cz', mobileCode: '420'},
    de: {country: 'Germany', ISO2: 'de', mobileCode: '49'},
    dj: {country: 'Djibouti', ISO2: 'dj', mobileCode: '253'},
    dk: {country: 'Denmark', ISO2: 'dk', mobileCode: '45'},
    dm: {country: 'Dominica', ISO2: 'dm', mobileCode: '1767'},
    do: {country: 'Dominican Republic', ISO2: 'do', mobileCode: '1809'},
    dz: {country: 'Algeria', ISO2: 'dz', mobileCode: '213'},
    ec: {country: 'Ecuador', ISO2: 'ec', mobileCode: '593'},
    ee: {country: 'Estonia', ISO2: 'ee', mobileCode: '372'},
    eg: {country: 'Egypt', ISO2: 'eg', mobileCode: '20'},
    er: {country: 'Eritrea', ISO2: 'er', mobileCode: '291'},
    es: {country: 'Spain', ISO2: 'es', mobileCode: '34'},
    et: {country: 'Ethiopia', ISO2: 'et', mobileCode: '251'},
    fi: {country: 'Finland', ISO2: 'fi', mobileCode: '358'},
    fj: {country: 'Fiji', ISO2: 'fj', mobileCode: '679'},
    fk: {country: 'Falkland Islands', ISO2: 'fk', mobileCode: '500'},
    fm: {country: 'Micronesia', ISO2: 'fm', mobileCode: '691'},
    fo: {country: 'Faroe Islands', ISO2: 'fo', mobileCode: '298'},
    fr: {country: 'Réunion', ISO2: 'fr', mobileCode: '262'},
    ga: {country: 'Gabon', ISO2: 'ga', mobileCode: '241'},
    gb: {country: 'United Kingdom', ISO2: 'gb', mobileCode: '44'},
    gd: {country: 'Grenada', ISO2: 'gd', mobileCode: '1473'},
    ge: {country: 'Georgia', ISO2: 'ge', mobileCode: '995'},
    gh: {country: 'Ghana', ISO2: 'gh', mobileCode: '233'},
    gi: {country: 'Gibraltar', ISO2: 'gi', mobileCode: '350'},
    gl: {country: 'Greenland', ISO2: 'gl', mobileCode: '299'},
    gm: {country: 'Gambia', ISO2: 'gm', mobileCode: '220'},
    gn: {country: 'Guinea', ISO2: 'gn', mobileCode: '224'},
    gq: {country: 'Equatorial Guinea', ISO2: 'gq', mobileCode: '240'},
    gr: {country: 'Greece', ISO2: 'gr', mobileCode: '30'},
    gt: {country: 'Guatemala', ISO2: 'gt', mobileCode: '502'},
    gw: {country: 'Guinea-Bissau', ISO2: 'gw', mobileCode: '245'},
    gy: {country: 'Guyana', ISO2: 'gy', mobileCode: '592'},
    hk: {country: 'Hong Kong', ISO2: 'hk', mobileCode: '852'},
    hn: {country: 'Honduras', ISO2: 'hn', mobileCode: '504'},
    hr: {country: 'Croatia', ISO2: 'hr', mobileCode: '385'},
    ht: {country: 'Haiti', ISO2: 'ht', mobileCode: '509'},
    hu: {country: 'Hungary', ISO2: 'hu', mobileCode: '36'},
    id: {country: 'Indonesia', ISO2: 'id', mobileCode: '62'},
    ie: {country: 'Ireland', ISO2: 'ie', mobileCode: '353'},
    il: {country: 'Israel', ISO2: 'il', mobileCode: '972'},
    in: {country: 'India', ISO2: 'in', mobileCode: '91'},
    io: {country: 'Diego Garcia', ISO2: 'io', mobileCode: '246'},
    iq: {country: 'Iraq', ISO2: 'iq', mobileCode: '964'},
    ir: {country: 'Iran', ISO2: 'ir', mobileCode: '98'},
    it: {country: 'Italy', ISO2: 'it', mobileCode: '39'},
    jm: {country: 'Jamaica', ISO2: 'jm', mobileCode: '1876'},
    jo: {country: 'Jordan', ISO2: 'jo', mobileCode: '962'},
    jp: {country: 'Japan', ISO2: 'jp', mobileCode: '81'},
    ke: {country: 'Kenya', ISO2: 'ke', mobileCode: '254'},
    kg: {country: 'Kyrgyzstan', ISO2: 'kg', mobileCode: '996'},
    kh: {country: 'Cambodia', ISO2: 'kh', mobileCode: '855'},
    ki: {country: 'Kiribati', ISO2: 'ki', mobileCode: '686'},
    km: {country: 'Comoros', ISO2: 'km', mobileCode: '269'},
    kn: {country: 'St. Kitts and Nevis', ISO2: 'kn', mobileCode: '1869'},
    kp: {country: 'North Korea', ISO2: 'kp', mobileCode: '850'},
    kr: {country: 'South Korea', ISO2: 'kr', mobileCode: '82'},
    kw: {country: 'Kuwait', ISO2: 'kw', mobileCode: '965'},
    ky: {country: 'Cayman Islands', ISO2: 'ky', mobileCode: '1345'},
    kz: {country: 'Kazakhstan', ISO2: 'kz', mobileCode: '7'},
    la: {country: 'Laos', ISO2: 'la', mobileCode: '856'},
    lb: {country: 'Lebanon', ISO2: 'lb', mobileCode: '961'},
    lc: {country: 'St. Lucia', ISO2: 'lc', mobileCode: '1758'},
    li: {country: 'Liechtenstein', ISO2: 'li', mobileCode: '423'},
    lk: {country: 'Sri Lanka', ISO2: 'lk', mobileCode: '94'},
    lr: {country: 'Liberia', ISO2: 'lr', mobileCode: '231'},
    ls: {country: 'Lesotho', ISO2: 'ls', mobileCode: '266'},
    lt: {country: 'Lithuania', ISO2: 'lt', mobileCode: '370'},
    lu: {country: 'Luxembourg', ISO2: 'lu', mobileCode: '352'},
    lv: {country: 'Latvia', ISO2: 'lv', mobileCode: '371'},
    ly: {country: 'Libya', ISO2: 'ly', mobileCode: '218'},
    ma: {country: 'Morocco', ISO2: 'ma', mobileCode: '212'},
    mc: {country: 'Monaco', ISO2: 'mc', mobileCode: '377'},
    md: {country: 'Moldova', ISO2: 'md', mobileCode: '373'},
    me: {country: 'Montenegro', ISO2: 'me', mobileCode: '382'},
    mg: {country: 'Madagascar', ISO2: 'mg', mobileCode: '261'},
    mh: {country: 'Marshall Islands', ISO2: 'mh', mobileCode: '692'},
    mk: {country: 'Macedonia', ISO2: 'mk', mobileCode: '389'},
    ml: {country: 'Mali', ISO2: 'ml', mobileCode: '223'},
    mm: {country: 'Burma', ISO2: 'mm', mobileCode: '95'},
    mn: {country: 'Mongolia', ISO2: 'mn', mobileCode: '976'},
    mo: {country: 'Macau', ISO2: 'mo', mobileCode: '853'},
    mp: {country: 'Mariana Island', ISO2: 'mp', mobileCode: '1670'},
    mr: {country: 'Mauritania', ISO2: 'mr', mobileCode: '222'},
    ms: {country: 'Montserrat', ISO2: 'ms', mobileCode: '1664'},
    mt: {country: 'Malta', ISO2: 'mt', mobileCode: '356'},
    mu: {country: 'Mauritius', ISO2: 'mu', mobileCode: '230'},
    mv: {country: 'Maldives', ISO2: 'mv', mobileCode: '960'},
    mw: {country: 'Malawi', ISO2: 'mw', mobileCode: '265'},
    mx: {country: 'Mexico', ISO2: 'mx', mobileCode: '52'},
    my: {country: 'Malaysia', ISO2: 'my', mobileCode: '60'},
    mz: {country: 'Mozambique', ISO2: 'mz', mobileCode: '258'},
    na: {country: 'Namibia', ISO2: 'na', mobileCode: '264'},
    nc: {country: 'New Caledonia', ISO2: 'nc', mobileCode: '687'},
    ne: {country: 'Niger', ISO2: 'ne', mobileCode: '227'},
    ng: {country: 'Nigeria', ISO2: 'ng', mobileCode: '234'},
    ni: {country: 'Nicaragua', ISO2: 'ni', mobileCode: '505'},
    nl: {country: 'Netherlands', ISO2: 'nl', mobileCode: '31'},
    no: {country: 'Norway', ISO2: 'no', mobileCode: '47'},
    np: {country: 'Nepal', ISO2: 'np', mobileCode: '977'},
    nr: {country: 'Nauru', ISO2: 'nr', mobileCode: '674'},
    nu: {country: 'Niue', ISO2: 'nu', mobileCode: '683'},
    nz: {country: 'New Zealand', ISO2: 'nz', mobileCode: '64'},
    om: {country: 'Oman', ISO2: 'om', mobileCode: '968'},
    pa: {country: 'Panama', ISO2: 'pa', mobileCode: '507'},
    pe: {country: 'Peru', ISO2: 'pe', mobileCode: '51'},
    ph: {country: 'Philippines', ISO2: 'ph', mobileCode: '63'},
    pk: {country: 'Pakistan', ISO2: 'pk', mobileCode: '92'},
    pl: {country: 'Poland', ISO2: 'pl', mobileCode: '48'},
    pm: {country: 'Saint-Pierre and Miquelon', ISO2: 'pm', mobileCode: '508'},
    pr: {country: 'Puerto Rico', ISO2: 'pr', mobileCode: '1'},
    ps: {country: 'Palestine', ISO2: 'ps', mobileCode: '970'},
    pt: {country: 'Portugal', ISO2: 'pt', mobileCode: '351'},
    pw: {country: 'Palau', ISO2: 'pw', mobileCode: '680'},
    py: {country: 'Paraguay', ISO2: 'py', mobileCode: '595'},
    qa: {country: 'Qatar', ISO2: 'qa', mobileCode: '974'},
    ro: {country: 'Romania', ISO2: 'ro', mobileCode: '40'},
    rs: {country: 'Serbia', ISO2: 'rs', mobileCode: '381'},
    ru: {country: 'Russia', ISO2: 'ru', mobileCode: '7'},
    rw: {country: 'Rwanda', ISO2: 'rw', mobileCode: '250'},
    sa: {country: 'Saudi Arabia', ISO2: 'sa', mobileCode: '966'},
    sb: {country: 'Solomon Islands', ISO2: 'sb', mobileCode: '677'},
    sc: {country: 'Seychelles', ISO2: 'sc', mobileCode: '248'},
    sd: {country: 'Sudan', ISO2: 'sd', mobileCode: '249'},
    se: {country: 'Sweden', ISO2: 'se', mobileCode: '46'},
    sg: {country: 'Singapore', ISO2: 'sg', mobileCode: '65'},
    sh: {country: 'St. Helena', ISO2: 'sh', mobileCode: '290'},
    si: {country: 'Slovenia', ISO2: 'si', mobileCode: '386'},
    sk: {country: 'Slovakia', ISO2: 'sk', mobileCode: '421'},
    sl: {country: 'Sierra Leone', ISO2: 'sl', mobileCode: '232'},
    sm: {country: 'San Marino', ISO2: 'sm', mobileCode: '378'},
    sn: {country: 'Senegal', ISO2: 'sn', mobileCode: '221'},
    so: {country: 'Somalia', ISO2: 'so', mobileCode: '252'},
    sr: {country: 'Surinam', ISO2: 'sr', mobileCode: '597'},
    st: {country: 'São Tomé and Príncipe', ISO2: 'st', mobileCode: '239'},
    sv: {country: 'El Salvador', ISO2: 'sv', mobileCode: '503'},
    sy: {country: 'Syria', ISO2: 'sy', mobileCode: '963'},
    sz: {country: 'Swaziland', ISO2: 'sz', mobileCode: '268'},
    tc: {country: 'Turks and Caicos Islands', ISO2: 'tc', mobileCode: '1649'},
    td: {country: 'Chad', ISO2: 'td', mobileCode: '235'},
    tg: {country: 'Togo', ISO2: 'tg', mobileCode: '228'},
    th: {country: 'Thailand', ISO2: 'th', mobileCode: '66'},
    tj: {country: 'Tajikistan', ISO2: 'tj', mobileCode: '992'},
    tl: {country: 'East Timor', ISO2: 'tl', mobileCode: '670'},
    tm: {country: 'Turkmenistan', ISO2: 'tm', mobileCode: '993'},
    tn: {country: 'Tunisia', ISO2: 'tn', mobileCode: '216'},
    to: {country: 'Tonga', ISO2: 'to', mobileCode: '676'},
    tr: {country: 'Turkey', ISO2: 'tr', mobileCode: '90'},
    tt: {country: 'Trinidad and Tobago', ISO2: 'tt', mobileCode: '1868'},
    tv: {country: 'Tuvalu', ISO2: 'tv', mobileCode: '688'},
    tw: {country: 'Taiwan', ISO2: 'tw', mobileCode: '886'},
    tz: {country: 'Tanzania', ISO2: 'tz', mobileCode: '255'},
    ua: {country: 'Ukraine', ISO2: 'ua', mobileCode: '380'},
    ug: {country: 'Uganda', ISO2: 'ug', mobileCode: '256'},
    us: {country: 'United States', ISO2: 'us', mobileCode: '1'},
    uy: {country: 'Uruguay', ISO2: 'uy', mobileCode: '598'},
    uz: {country: 'Uzbekistan', ISO2: 'uz', mobileCode: '998'},
    va: {country: 'Vatican City', ISO2: 'va', mobileCode: '39'},
    vc: {country: 'St. Vincent and the Grenadines', ISO2: 'vc', mobileCode: '1784'},
    ve: {country: 'Venezuela', ISO2: 've', mobileCode: '58'},
    vg: {country: 'British Virgin Islands', ISO2: 'vg', mobileCode: '1284'},
    vi: {country: 'Virgin Islands', ISO2: 'vi', mobileCode: '1340'},
    vn: {country: 'Vietnam', ISO2: 'vn', mobileCode: '84'},
    vu: {country: 'Vanuatu', ISO2: 'vu', mobileCode: '678'},
    wf: {country: 'Wallis and Futuna', ISO2: 'wf', mobileCode: '681'},
    ws: {country: 'Samoa', ISO2: 'ws', mobileCode: '685'},
    xk: {country: 'Kosovo', ISO2: 'xk', mobileCode: '381'},
    ye: {country: 'Yemen', ISO2: 'ye', mobileCode: '967'},
    za: {country: 'South Africa', ISO2: 'za', mobileCode: '27'},
    zm: {country: 'Zambia', ISO2: 'zm', mobileCode: '260'},
    zw: {country: 'Zimbabwe', ISO2: 'zw', mobileCode: '263'},
};